### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by torjusti** [toastedcrumpets/BlackboardQuizMaker#1] opened 2017-06-22 06:56 UTC
Hi, would you be willing to add a license to this repository?

**Comment by toastedcrumpets** [comment] 2017-06-28 20:16
Sure, I'll add a promiscuous one now. Out of interest, what are you going to do with it?

**Comment by toastedcrumpets** [comment] 2017-06-28 20:18
Closed by commit 9b7de749dd30bcebc6050f7b34feb7c92505ab76.
Feel free to still reply even though the issue is closed.

**Closed as completed by toastedcrumpets** 2017-06-28 20:18 UTC
